deploy:
  branch:
    server: deploy.droman.stark.vps-private.net
    username: droman
    dir: '{home}/github/{repo_owner}/{repo_name}/branch/{branch}'
    env_vars:
      docroot: '{home}/domains/deploy.droman.stark.vps-private.net'
      domain: 'deploy.droman.stark.vps-private.net'
      database_name: droman_deploy
      database_user: droman_deploy
      database_pass: 
      account_user: admin
      account_mail: admin@deploy.droman.stark.vps-private.net
      account_pass: 
      site_mail: info@deploy.droman.stark.vps-private.net
      site_name: TestDeploy
      default_theme: "bartik"
      enable_devel: ""      
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'

